### ISSUE TITLE
Bump DataStructures compat

### ISSUE THREAD

**Issue by fgasdia** [Azzaare/BibParser.jl#10]
CompatHelper built PR #6 to bump the compat version of DataStructures a couple of months ago. Is there any reason not to accept this? It's preventing some other packages in my docs Project from updating and leading to precompilation issues and other warnings.

**Comment by Azzaare** [comment]
@fgasdia the only reason is that I missed the notification.

Thank you for the reminder.

Let me know if it causes any more version trouble
